### ISSUE TITLE
Add Digest  Authentication support

### ISSUE THREAD

**Issue by ehabtanta** [damuellen/FritzTR064#1]
hi sir i would like to use your app with a non fritz device it works so similar to your devices but it uses digest auth and i cannot find ant tr064 client for it 

so can u pleas add digest auth to the app 

thanks

**Comment by damuellen** [comment]
hi the app uses digest auth see line 125 of TR064.swift, but you can't set the password in the app. But I will implement this in the next week.

**Comment by ehabtanta** [comment]
perfect 
but it was my bad that i didn't notice it was for ios 

is there any possibility to make it run in windows /LUNIX or android ?
